/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin;

import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Expenses extends javax.swing.JFrame {

    /**
     * Creates new form report
     */
    double totalExpenses = 0;

    public Expenses() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        maintenanceTF = new javax.swing.JTextField();
        cleaningTF = new javax.swing.JTextField();
        utilityTF = new javax.swing.JTextField();
        otherTF = new javax.swing.JTextField();
        salaryTF = new javax.swing.JTextField();
        generateReportButton = new javax.swing.JButton();
        month = new javax.swing.JLabel();
        generateReportButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("Cleaning and Laundry:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setText("Maintenance and Repairs:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("Staff Wages:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 153));
        jLabel5.setText("Utilities:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Fill in the Monthly Expenses for");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 153));
        jLabel7.setText("Others:");

        maintenanceTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maintenanceTFActionPerformed(evt);
            }
        });

        generateReportButton.setBackground(new java.awt.Color(0, 102, 102));
        generateReportButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        generateReportButton.setForeground(new java.awt.Color(255, 255, 255));
        generateReportButton.setText("Generate Report");
        generateReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateReportButtonActionPerformed(evt);
            }
        });

        month.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        month.setForeground(new java.awt.Color(0, 102, 102));

        generateReportButton1.setBackground(new java.awt.Color(0, 102, 102));
        generateReportButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        generateReportButton1.setForeground(new java.awt.Color(255, 255, 255));
        generateReportButton1.setText("BACK");
        generateReportButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateReportButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("RM");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("RM");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setText("RM");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 102));
        jLabel10.setText("RM");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 102));
        jLabel11.setText("RM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(generateReportButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(utilityTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(salaryTF, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(maintenanceTF, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cleaningTF, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(otherTF))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(generateReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 76, Short.MAX_VALUE))
                    .addComponent(month, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(generateReportButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cleaningTF, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(maintenanceTF, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(salaryTF, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(48, 48, 48))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(utilityTF, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel10)))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(otherTF, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generateReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void maintenanceTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maintenanceTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maintenanceTFActionPerformed

    private void generateReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateReportButtonActionPerformed
        // TODO add your handling code here:
        try {
            String cleaning = cleaningTF.getText();
            String maintenance = maintenanceTF.getText();
            String salary = salaryTF.getText();
            String utility = utilityTF.getText();
            String other = otherTF.getText();

            // Check if any field is empty
            if (cleaning.isEmpty() || maintenance.isEmpty() || salary.isEmpty() || utility.isEmpty() || other.isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "Please fill in all fields, fill in 0 if no expenses");
                return;
            }

            double totalExpenses;
            try {
                totalExpenses = Double.parseDouble(cleaning) + Double.parseDouble(maintenance) + Double.parseDouble(salary) + Double.parseDouble(utility) + Double.parseDouble(other);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(rootPane, "Invalid input format. Please enter numbers only.");
                return;
            }

            Report report = new Report();
            report.setVisible(true);
            Report.totalExpensesTF.setText(Double.toString(totalExpenses));
            MonthlyReport monthlyReport = new MonthlyReport();
            monthlyReport.setTotalExpenses(totalExpenses);
            double profit = monthlyReport.getTotalRental() - totalExpenses;

            System.out.println(monthlyReport.getMasterRoomOccupancy());
            Report.month.setText(monthlyReport.getMonth());
            Report.masterRoomOccupancy.setText(Integer.toString(monthlyReport.getMasterRoomOccupancy()));
            Report.juniorRoomOccupancy.setText(Integer.toString(monthlyReport.getJuniorRoomOccupancy()));
            Report.singleRoomOccupancy.setText(Integer.toString(monthlyReport.getSingleRoomOccupancy()));
            Report.totalRoomOccupied.setText(Integer.toString(monthlyReport.getTotalRoomOccupancy()));
            Report.totalRental.setText(Double.toString(monthlyReport.getTotalRental()));
            Report.totalProfit.setText(Double.toString(profit));

            String monthData = monthlyReport.getMonth();
            String masterData = Integer.toString(monthlyReport.getMasterRoomOccupancy());
            String juniorData = Integer.toString(monthlyReport.getJuniorRoomOccupancy());
            String singleData = Integer.toString(monthlyReport.getSingleRoomOccupancy());
            String totalOccupancyData = Integer.toString(monthlyReport.getTotalRoomOccupancy());
            String totalRentalData = Double.toString(monthlyReport.getTotalRental());
            String totalExpensesData = Double.toString(totalExpenses);
            String totalProfitData = Double.toString(profit);
            String allReportData = monthData + "," + masterData + "," + juniorData + "," + singleData + "," + totalOccupancyData + "," + totalRentalData + "," + totalExpensesData + "," + totalProfitData;
            MonthlyReport.writeReportInfo(allReportData, "MonthlyReport.txt");

            this.setVisible(false);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Invalid input format. Please enter numbers only.");
            return;
        }


    }//GEN-LAST:event_generateReportButtonActionPerformed

    private void generateReportButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateReportButton1ActionPerformed
        // TODO add your handling code here:
        GenerateMonthlyReport generateReport = new GenerateMonthlyReport();
        generateReport.setVisible(true);
        this.setVisible(false);
        RoomInformation.generateReportTable(GenerateMonthlyReport.model, "ApprovedHostelApplication.txt");


    }//GEN-LAST:event_generateReportButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cleaningTF;
    private javax.swing.JButton generateReportButton;
    private javax.swing.JButton generateReportButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField maintenanceTF;
    public static javax.swing.JLabel month;
    private javax.swing.JTextField otherTF;
    private javax.swing.JTextField salaryTF;
    private javax.swing.JTextField utilityTF;
    // End of variables declaration//GEN-END:variables
}
