/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class GenerateMonthlyReport extends javax.swing.JFrame {

    /**
     * Creates new form GenerateMonthlyReport
     */
    public static DefaultTableModel model;
    public GenerateMonthlyReport() {
        initComponents();
        model = (DefaultTableModel) monthlyReportTable.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        monthlyReportTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        monthlyReportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Months", "Single Room Occupancy", "Junior Room Occupancy", "Master Room Occupancy", "Total Room Occupancy", "Total Rental Collected"
            }
        ));
        monthlyReportTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                monthlyReportTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(monthlyReportTable);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Monthly Report");

        backButton.setBackground(new java.awt.Color(0, 102, 102));
        backButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 923, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(280, 280, 280)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        Menu mainMenu = new Menu();
        mainMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed

    private void monthlyReportTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monthlyReportTableMouseClicked
        // TODO add your handling code here:
        int index = monthlyReportTable.getSelectedRow();
        String monthYear = model.getValueAt(index, 0).toString();
        String singleRoomOccupancy = model.getValueAt(index, 1).toString();
        String juniorRoomOccupancy = model.getValueAt(index, 2).toString();
        String masterRoomOccupancy = model.getValueAt(index, 3).toString();
        String totalRoomOccupancy = model.getValueAt(index, 4).toString();
        String totalRental = model.getValueAt(index, 5).toString();
        
        Expenses expenses = new Expenses();
        expenses.setVisible(true);
        expenses.month.setText(monthYear);
        this.setVisible(false);
        

        MonthlyReport monthlyReport = new MonthlyReport();
        monthlyReport.setMonth(monthYear);
        monthlyReport.setMasterRoomOccupancy(Integer.parseInt(masterRoomOccupancy));
        monthlyReport.setJuniorRoomOccupancy(Integer.parseInt(juniorRoomOccupancy));
        monthlyReport.setSingleRoomOccupancy(Integer.parseInt(singleRoomOccupancy));
        monthlyReport.setTotalRental(Double.parseDouble(totalRental));
        monthlyReport.setTotalRoomOccupancy(Integer.parseInt(totalRoomOccupancy));
//        Report.month.setText(monthYear);
//        Report.masterRoomOccupancy.setText(masterRoomOccupancy);
//        Report.juniorRoomOccupancy.setText(juniorRoomOccupancy);
//        Report.singleRoomOccupancy.setText(singleRoomOccupancy);
//        Report.totalRental.setText(totalRental);
       
        
        
        
        
    }//GEN-LAST:event_monthlyReportTableMouseClicked

    /**
     * @param args the command line arguments
     */
   
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable monthlyReportTable;
    // End of variables declaration//GEN-END:variables
}
