/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin;

import static Admin.ReviewNewApplication.model;
import Student.Request;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class MaintenanceRequestReview extends javax.swing.JFrame {

    /**
     * Creates new form MaintenanceRequestMenu
     */
    public static DefaultTableModel model;

    public MaintenanceRequestReview() {
        initComponents();
        model = (DefaultTableModel) maintenanceRequestTable.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        maintenanceRequestTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        submitButtonTF = new javax.swing.JButton();
        commentTF = new javax.swing.JTextField();
        backButtonTF = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        maintenanceRequestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Request ID", "Request Date", "Room No", "Request", "Comment"
            }
        ));
        maintenanceRequestTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maintenanceRequestTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(maintenanceRequestTable);

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Maintenance Request");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Add Your Comment:");

        submitButtonTF.setBackground(new java.awt.Color(0, 102, 102));
        submitButtonTF.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        submitButtonTF.setForeground(new java.awt.Color(255, 255, 255));
        submitButtonTF.setText("SUBMIT");
        submitButtonTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonTFActionPerformed(evt);
            }
        });

        backButtonTF.setBackground(new java.awt.Color(0, 102, 102));
        backButtonTF.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        backButtonTF.setForeground(new java.awt.Color(255, 255, 255));
        backButtonTF.setText("BACK");
        backButtonTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonTFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(backButtonTF))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(commentTF)))
                                .addGap(18, 18, 18)
                                .addComponent(submitButtonTF)
                                .addGap(10, 10, 10)))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backButtonTF, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(commentTF, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitButtonTF, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void maintenanceRequestTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maintenanceRequestTableMouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_maintenanceRequestTableMouseClicked

    private void submitButtonTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonTFActionPerformed
        // TODO add your handling code here:
        int selectedIndex = maintenanceRequestTable.getSelectedRow();
        if (selectedIndex != -1) {
            String requestID = model.getValueAt(selectedIndex, 0).toString();
            String requestDate = model.getValueAt(selectedIndex, 1).toString();
            String roomID = model.getValueAt(selectedIndex, 0).toString();
            String requestData = model.getValueAt(selectedIndex, 0).toString();
            String comment = commentTF.getText();

            // Remove comma from the comment if present
            comment = comment.replace(",", "");

            String commentedRequest = requestID + "," + requestDate + "," + roomID + "," + requestData + "," + comment;
            Request request = new Request();

            // request.writeRequest(commentedRequest, "ReviewedRequest.txt");
            Request.updateRowInFile("AllMaintenanceRequest.txt", requestID, comment);

            JOptionPane.showMessageDialog(rootPane, "Comment Submitted");
            commentTF.setText("");
            model.removeRow(maintenanceRequestTable.getSelectedRow());
            request.write(model, "NewMaintenanceRequest.txt");
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row to submit your comment.");
        }


    }//GEN-LAST:event_submitButtonTFActionPerformed

    private void backButtonTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonTFActionPerformed
        // TODO add your handling code here:
        MaintenanceRequestMenu maintenanceRequestMenu = new MaintenanceRequestMenu();
        maintenanceRequestMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backButtonTFActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButtonTF;
    private javax.swing.JTextField commentTF;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable maintenanceRequestTable;
    private javax.swing.JButton submitButtonTF;
    // End of variables declaration//GEN-END:variables
}
