/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin;

import Student.User;
import static Student.User.allStudent;

/**
 *
 * @author User
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        manageRoom = new javax.swing.JButton();
        manageRoomID = new javax.swing.JButton();
        manageStudentApplication = new javax.swing.JButton();
        checkStudentRecord = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        manageAccount = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        GenerateReport = new javax.swing.JButton();
        GenerateReport1 = new javax.swing.JButton();
        reviewMaintenanceReport = new javax.swing.JButton();
        reviewMaintenanceReport1 = new javax.swing.JButton();
        viewAllRegisteredStudent = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setForeground(new java.awt.Color(0, 153, 153));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(0, 153, 153));

        manageRoom.setBackground(new java.awt.Color(0, 153, 153));
        manageRoom.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        manageRoom.setForeground(new java.awt.Color(255, 255, 255));
        manageRoom.setText("Manage Room");
        manageRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageRoomActionPerformed(evt);
            }
        });

        manageRoomID.setBackground(new java.awt.Color(0, 153, 153));
        manageRoomID.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        manageRoomID.setForeground(new java.awt.Color(255, 255, 255));
        manageRoomID.setText("Manage Room ID");
        manageRoomID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageRoomIDActionPerformed(evt);
            }
        });

        manageStudentApplication.setBackground(new java.awt.Color(0, 153, 153));
        manageStudentApplication.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        manageStudentApplication.setForeground(new java.awt.Color(255, 255, 255));
        manageStudentApplication.setText("Manage Student's Application");
        manageStudentApplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageStudentApplicationActionPerformed(evt);
            }
        });

        checkStudentRecord.setBackground(new java.awt.Color(0, 153, 153));
        checkStudentRecord.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        checkStudentRecord.setForeground(new java.awt.Color(255, 255, 255));
        checkStudentRecord.setText("Check Student's Record");
        checkStudentRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkStudentRecordActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("Menu");

        manageAccount.setBackground(new java.awt.Color(0, 153, 153));
        manageAccount.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        manageAccount.setForeground(new java.awt.Color(255, 255, 255));
        manageAccount.setText("Manage Account");
        manageAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageAccountActionPerformed(evt);
            }
        });

        backButton.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        backButton.setForeground(new java.awt.Color(0, 153, 153));
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        GenerateReport.setBackground(new java.awt.Color(0, 153, 153));
        GenerateReport.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        GenerateReport.setForeground(new java.awt.Color(255, 255, 255));
        GenerateReport.setText("Generate Report");
        GenerateReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateReportActionPerformed(evt);
            }
        });

        GenerateReport1.setBackground(new java.awt.Color(0, 153, 153));
        GenerateReport1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        GenerateReport1.setForeground(new java.awt.Color(255, 255, 255));
        GenerateReport1.setText("View Historical Report");
        GenerateReport1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateReport1ActionPerformed(evt);
            }
        });

        reviewMaintenanceReport.setBackground(new java.awt.Color(0, 153, 153));
        reviewMaintenanceReport.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        reviewMaintenanceReport.setForeground(new java.awt.Color(255, 255, 255));
        reviewMaintenanceReport.setText("Room Maintenance Request");
        reviewMaintenanceReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reviewMaintenanceReportActionPerformed(evt);
            }
        });

        reviewMaintenanceReport1.setBackground(new java.awt.Color(0, 153, 153));
        reviewMaintenanceReport1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        reviewMaintenanceReport1.setForeground(new java.awt.Color(255, 255, 255));
        reviewMaintenanceReport1.setText("Waiting List Application");
        reviewMaintenanceReport1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reviewMaintenanceReport1ActionPerformed(evt);
            }
        });

        viewAllRegisteredStudent.setBackground(new java.awt.Color(0, 153, 153));
        viewAllRegisteredStudent.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        viewAllRegisteredStudent.setForeground(new java.awt.Color(255, 255, 255));
        viewAllRegisteredStudent.setText("View All Registered Student");
        viewAllRegisteredStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAllRegisteredStudentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(228, 228, 228)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(manageAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(manageRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(manageRoomID, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(manageStudentApplication))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(checkStudentRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GenerateReport, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(reviewMaintenanceReport1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(reviewMaintenanceReport, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                            .addComponent(GenerateReport1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(viewAllRegisteredStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manageAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GenerateReport, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(manageRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reviewMaintenanceReport, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GenerateReport1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageRoomID, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(reviewMaintenanceReport1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(manageStudentApplication, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkStudentRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewAllRegisteredStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void manageRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageRoomActionPerformed

        ManageCategory manageCategory = new ManageCategory();
        manageCategory.setVisible(true);
        this.setVisible(false);
        RoomInformation roomInfo = new RoomInformation();
        roomInfo.display(ManageCategory.model,
                "RoomCategory.txt");
//        RoomInformation.roomCountForEachCategory();
    }//GEN-LAST:event_manageRoomActionPerformed

    private void manageRoomIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageRoomIDActionPerformed
        // TODO add your handling code here:
        RoomInformation.roomCountForEachCategory();
        ManageRoomID manageRoomId = new ManageRoomID();
        RoomInformation.display(ManageRoomID.roomCategoryDropDownList);
        ManageRoomID.roomCategoryDropDownList.setSelectedIndex(-1);
        manageRoomId.setVisible(true);
        this.setVisible(false);
        RoomInformation roomInfo = new RoomInformation();
        roomInfo.display(ManageRoomID.model, "RoomID.txt");


    }//GEN-LAST:event_manageRoomIDActionPerformed

    private void manageStudentApplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageStudentApplicationActionPerformed
        // TODO add your handling code here:
        ManageStudentApplicationMenu manageApplication = new ManageStudentApplicationMenu();
        manageApplication.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_manageStudentApplicationActionPerformed

    private void manageAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageAccountActionPerformed
        UpdateAdmin update = new UpdateAdmin();
        update.setVisible(true);
        UpdateAdmin.adminName.setText(HostelManagementSystem.loginAsAdmin.getName());
        UpdateAdmin.adminPassword.setText(HostelManagementSystem.loginAsAdmin.getPassword());
        this.setVisible(false);

    }//GEN-LAST:event_manageAccountActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        Login loginPage = new Login();
        loginPage.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_backButtonActionPerformed

    private void checkStudentRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkStudentRecordActionPerformed
        // TODO add your handling code here:
        CheckStudentFees checkStudentFees = new CheckStudentFees();
        CheckStudentFees.paymentStatusDropDownList.insertItemAt("", 0);
        CheckStudentFees.paymentStatusDropDownList.setSelectedIndex(0);
        checkStudentFees.setVisible(true);
        this.setVisible(false);


    }//GEN-LAST:event_checkStudentRecordActionPerformed

    private void GenerateReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateReportActionPerformed
        GenerateMonthlyReport generateReport = new GenerateMonthlyReport();
        generateReport.setVisible(true);
// TODO add your handling code here:
        RoomInformation.generateReportTable(GenerateMonthlyReport.model, "ApprovedHostelApplication.txt");
        this.setVisible(false);
    }//GEN-LAST:event_GenerateReportActionPerformed

    private void GenerateReport1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateReport1ActionPerformed
        // TODO add your handling code here:
        HistoricalReport historicalReport = new HistoricalReport();
        historicalReport.setVisible(true);
        this.setVisible(false);
        MonthlyReport.displayReportData(HistoricalReport.model, "MonthlyReport.txt");
    }//GEN-LAST:event_GenerateReport1ActionPerformed

    private void reviewMaintenanceReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reviewMaintenanceReportActionPerformed
        // TODO add your handling code here:
        MaintenanceRequestMenu maintenanceRequestMenu = new MaintenanceRequestMenu();
        maintenanceRequestMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_reviewMaintenanceReportActionPerformed

    private void reviewMaintenanceReport1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reviewMaintenanceReport1ActionPerformed
        ReviewWaitingList waitingList = new ReviewWaitingList();
        waitingList.setVisible(true);
        RoomInformation.displayBookingInfo(ReviewWaitingList.model1, "studentWaitingList.txt");
        RoomInformation.displayAvailableRoom(ReviewWaitingList.model2,
                "RoomAvailable.txt");
        this.setVisible(false);


    }//GEN-LAST:event_reviewMaintenanceReport1ActionPerformed

    private void viewAllRegisteredStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAllRegisteredStudentActionPerformed
        // TODO add your handling code here:
        RegisteredStudent registeredStudent = new RegisteredStudent();
        registeredStudent.setVisible(true);

        for (User userDetails : allStudent) {
            // Format the contact number with leading zero
            String contactNumber = String.valueOf(userDetails.getContact());
            if (!contactNumber.startsWith("0")) {
                contactNumber = "0" + contactNumber;
            }

            RegisteredStudent.model.addRow(new Object[]{userDetails.getName(), userDetails.getEmail(), userDetails.getStudentID(), userDetails.getGender(), contactNumber});
        }

        this.setVisible(false);

    }//GEN-LAST:event_viewAllRegisteredStudentActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GenerateReport;
    private javax.swing.JButton GenerateReport1;
    private javax.swing.JButton backButton;
    private javax.swing.JButton checkStudentRecord;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton manageAccount;
    private javax.swing.JButton manageRoom;
    private javax.swing.JButton manageRoomID;
    private javax.swing.JButton manageStudentApplication;
    private javax.swing.JButton reviewMaintenanceReport;
    private javax.swing.JButton reviewMaintenanceReport1;
    private javax.swing.JButton viewAllRegisteredStudent;
    // End of variables declaration//GEN-END:variables
}
