/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Student;

import Admin.HostelManagementSystem;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class BookingStatus extends javax.swing.JFrame {

    /**
     * Creates new form BookingStatus
     */
    public static DefaultTableModel model;

    public BookingStatus() {
        initComponents();
        model = (DefaultTableModel) bookingStatusTable.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bookingStatusTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        bookingStatusTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Booking ID", "Booking Date", "Room Type", "Tenancy Period", "Starting Date", "End Date", "Booking Status", "Room Number", "Fees", "Payment Status"
            }
        ));
        bookingStatusTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookingStatusTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(bookingStatusTable);
        if (bookingStatusTable.getColumnModel().getColumnCount() > 0) {
            bookingStatusTable.getColumnModel().getColumn(0).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("My Booking Status");

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 153, 153));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Pay");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton1)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1037, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addComponent(jLabel1)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jButton1)
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        StudentMenu studentMenu = new StudentMenu();
        studentMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bookingStatusTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookingStatusTableMouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_bookingStatusTableMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (bookingStatusTable.getSelectedRowCount() == 1) {
            Object[] bookingData = BookingFunction.readRoomInfo("ApprovedHostelApplication.txt");
            int index = bookingStatusTable.getSelectedRow();
            // Get value from JTable
            String totalFees = model.getValueAt(index, 8).toString();
            Double convertTotalFees = Double.parseDouble(totalFees);

            // Get the selected row index
            int selectedIndex = bookingStatusTable.getSelectedRow();
            String pendingStatus = model.getValueAt(selectedIndex, 6).toString();

            if (pendingStatus.equals("Rejected")) {
                JOptionPane.showMessageDialog(null, "Your application has been rejected, no payment is allowed.");
            } else if (pendingStatus.equals("waitingList...")) {
                JOptionPane.showMessageDialog(null, "Your application is still in waiting list, no payment is allowed.");
            } else if (!pendingStatus.equals("pending")) {

                String paymentStatus = model.getValueAt(selectedIndex, 9).toString();

                if (paymentStatus.equals("Paid")) {
                    JOptionPane.showMessageDialog(null, "Payment has already been made for this row.");
                } else {
                    int maxAttempts = 3;
                    int incorrectAttempts = 0;

                    while (incorrectAttempts < maxAttempts) {
                        try {
                            double paymentAmount = 0.0;
                            String input = JOptionPane.showInputDialog("Payment Amount RM: " + totalFees + "\nEnter payment amount:");

                            if (input != null) {
                                paymentAmount = Double.parseDouble(input);

                                if (paymentAmount == convertTotalFees) {
                                    // Update the value in the JTable model
                                    model.setValueAt("Paid", selectedIndex, 9);
                                    String userBookingID = model.getValueAt(selectedIndex, 0).toString();

                                    // Display success message
                                    JOptionPane.showMessageDialog(null, "Payment Success!");
                                    BookingFunction bookingFunction = new BookingFunction();
                                    bookingFunction.update("ApprovedHostelApplication.txt", userBookingID);
                                    bookingFunction.update("AllStudentBooking.txt", userBookingID);
                                    break;
                                } else {
                                    // Display error message for incorrect payment amount
                                    JOptionPane.showMessageDialog(rootPane, "Invalid payment amount!");
                                    incorrectAttempts++;
                                }
                            } else {
                                // User canceled the payment
                                break;
                            }
                        } catch (NumberFormatException ex) {
                            JOptionPane.showMessageDialog(rootPane, "Invalid payment amount!");
                            incorrectAttempts++;
                        } catch (RuntimeException ex) {
                            JOptionPane.showMessageDialog(rootPane, "Invalid payment amount!");
                            incorrectAttempts++;
                        }
                    }

                    if (incorrectAttempts == maxAttempts) {
                        JOptionPane.showMessageDialog(rootPane, "Exceeded maximum attempts. Payment canceled.");
                    }
                }

            } else {
                JOptionPane.showMessageDialog(null, "Your application has not yet been approved!");
            }

        } else {
            if (bookingStatusTable.getRowCount() == 0) {
                // if table is empty (no data) then display message
                JOptionPane.showMessageDialog(rootPane, "The Table is Empty!");
            } else {
                // if table is not empty but row is not selected or multiple row is selected
                JOptionPane.showMessageDialog(rootPane, "Please select the row you want to pay!");
            }
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bookingStatusTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
